#!/bin/sh
### BEGIN INIT INFO
# Provides:          specAVS
# Required-Start:    $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Starts and stops specAVS service
### END INIT INFO

FILE_NAME=spectral

PIDFILE=/var/run/$FILE_NAME.pid
DAEMON=/home/pi/specAVS/$FILE_NAME

start() {
    echo "Starting specAVS..."
    start-stop-daemon --start --background --quiet --oknodo --retry forever/TERM --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- 1
}

stop() {
    echo "Stopping specAVS..."
    start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
    rm $PIDFILE
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 2
esac

exit 0

